<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="chassis">
    <!-- Includes -->
    <xacro:include filename="$(find mavric_launch)/urdf/inertia.xacro"/>
    <xacro:include filename="$(find mavric_launch)/urdf/constants.xacro"/>

    <!-- Chassis link -->
    <link name="chassis_link">
        <xacro:box_inertia mass="${chassis_mass}" length="${chassis_length}" width="${chassis_width}" height="${chassis_height}">
            <origin xyz="${com_x} ${com_y} ${com_z}" rpy="0 0 0" />
		</xacro:box_inertia>

		<visual> <!-- Chassis Tower -->
			<origin xyz="0 0 ${chassis_tower_height / 2}" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_tower_length} ${chassis_width} ${chassis_tower_height}" />
			</geometry>
		</visual>

        <visual> <!-- Chassis Payload -->
            <origin xyz="${chassis_tower_length / 2 + chassis_payload_length / 2} 0 ${chassis_payload_height / 2}" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_payload_length} ${chassis_width} ${chassis_payload_height}" />
            </geometry>
        </visual>

        <visual> <!-- Chassis Electrical -->
            <origin xyz="${-chassis_tower_length / 2 - chassis_electrical_length / 2} 0 ${chassis_electrical_height / 2}" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_electrical_length} ${chassis_width} ${chassis_electrical_height}" />
            </geometry>
        </visual>

        <visual> <!-- Chassis Caster -->
            <origin xyz="${-chassis_tower_length / 2 - chassis_electrical_length - chassis_caster_length / 2} 
                         0 
                         ${chassis_caster_height / 2 + chassis_caster_z_offset}" 
                         rpy="0 0 0" />
            <geometry>
                <box size="${chassis_caster_length} ${chassis_width} ${chassis_caster_height}" />
            </geometry>
        </visual>

		<collision>
			<origin xyz="${chassis_tower_length / 2 + chassis_payload_length - chassis_length / 2} 
                         0 
                         ${chassis_tower_height / 2}" 
                    rpy="0 0 0" />
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_tower_height}" />
			</geometry>
		</collision>
	</link>

    <joint name="chassis_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis_link" />
    </joint>

    
    <!-- Chassis color -->
    <gazebo reference="chassis_link">
        <material>Gazebo/Blue</material>
    </gazebo>
</robot>