<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="constants">
    <!-- Chassis Constants -->
    <xacro:property name="chassis_length" value="${45.5*0.0254}" />
    <xacro:property name="chassis_width" value="${24*0.0254}" />
    <xacro:property name="chassis_height" value="${22*0.0254}" />
    <xacro:property name="chassis_z_offset" value="${4.375*0.0254}" />

    <xacro:property name="chassis_tower_length" value="${8*0.0254}" />
    <xacro:property name="chassis_tower_height" value="${31*0.0254}" />

    <xacro:property name="chassis_payload_length" value="${14.25*0.0254}" />
    <xacro:property name="chassis_payload_height" value="${8*0.0254}" />

    <xacro:property name="chassis_electrical_length" value="${15.25*0.0254}" />
    <xacro:property name="chassis_electrical_height" value="${22*0.0254}" />

    <xacro:property name="chassis_caster_length" value="${8*0.0254}" />
    <xacro:property name="chassis_caster_height" value="${2.25*0.0254}" />
    <xacro:property name="chassis_caster_z_offset" value="${2*0.0254}" />

    <!-- Chassis Inertial Constants -->
    <xacro:property name="chassis_mass" value="29.9371" />
    <xacro:property name="com_x" value="${-4.0*0.0254}" />
    <xacro:property name="com_y" value="0.0" />
    <xacro:property name="com_z" value="${6.1875*0.0254-chassis_z_offset}" />

	<!-- Caster Constants -->
    <xacro:property name="caster_x_offset" value="${-24.625*0.0254}" />
    <xacro:property name="caster_radius" value="${3.5*0.0254}" />
    <xacro:property name="caster_mass" value="0.1" />

	<!-- Wheel Constants -->
    <xacro:property name="wheel_radius" value="${6.1875*0.0254}" />
    <xacro:property name="wheel_width" value="${4*0.0254}" />
    <xacro:property name="wheel_mass" value="5" />
    <xacro:property name="track_width" value="${31*0.0254}" />

    <!-- Lidar Constants -->
    <xacro:property name="lidar_height" value="${32.55*0.0254}"/>

    <!-- Camera Constants -->
    <xacro:property name="camera_mass" value="0.230"/>
    <xacro:property name="camera_length" value="0.04310"/>
    <xacro:property name="camera_width" value="0.17525"/>
    <xacro:property name="camera_height" value="0.03025"/>
    <xacro:property name="camera_angle" value="${10 * 0.01745327777}"/>
    <xacro:property name="camera_x_offset" value="${(4+2.66916)*0.0254}"/> 
    <xacro:property name="camera_z_offset" value="${(31-1.80395)*0.0254}"/> 

    <!-- IMU Constants -->
    <xacro:property name="imu_mass" value="0.025"/>
    <xacro:property name="imu_length" value="0.05"/>
    <xacro:property name="imu_width" value="0.03"/>
    <xacro:property name="imu_height" value="0.01"/>
</robot>