<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="plugins">
	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<update_rate>100.0</update_rate>
			<robot_base_frame>base_link</robot_base_frame>
			<command_topic>cmd_vel</command_topic>

			<left_joint>left_wheel_joint</left_joint>
			<right_joint>right_wheel_joint</right_joint>
			<wheel_separation>${track_width}</wheel_separation>
			<wheel_diameter>${2 * wheel_radius}</wheel_diameter>
			<publish_tf>true</publish_tf>
			<publish_wheel_tf>true</publish_wheel_tf>

			<max_wheel_acceleration>1.8</max_wheel_acceleration>
			<max_wheel_torque>30</max_wheel_torque>

			<odometrySource>encoder</odometrySource>
			<odometry_topic>odom</odometry_topic>
			<odometry_frame>odom</odometry_frame>
			<publish_odom>true</publish_odom>
			<publish_odom_tf>true</publish_odom_tf>

			<legacy_mode>false</legacy_mode>
			<ros_debug_level>na</ros_debug_level>
		</plugin>
	</gazebo>
</robot>